# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations

def load_blacklist(apps, schema_editor):
    WatsonBlacklist = apps.get_model("spaceoutvr", "WatsonBlacklist")
    b = WatsonBlacklist(text="")
    b.save()
    b = WatsonBlacklist(text="facebook")
    b.save()
    b = WatsonBlacklist(text="facebook page")
    b.save()
    b = WatsonBlacklist(text="official facebook page")
    b.save()
    b = WatsonBlacklist(text="facebook official page");
    b.save()
    b = WatsonBlacklist(text="official page")
    b.save()
    b = WatsonBlacklist(text="official")
    b.save()
    b = WatsonBlacklist(text="twitter")
    b.save()
    b = WatsonBlacklist(text="new york")
    b.save()
    b = WatsonBlacklist(text="new york city")
    b.save()
    b = WatsonBlacklist(text="ny")
    b.save()
    b = WatsonBlacklist(text="troy")
    b.save()
    b = WatsonBlacklist(text="youtube")
    b.save()
    b = WatsonBlacklist(text="google")
    b.save()
    b = WatsonBlacklist(text="official fan page")
    b.save()
    b = WatsonBlacklist(text="albany")
    b.save()
    b = WatsonBlacklist(text="CAPITAL REGION")
    b.save()
    b = WatsonBlacklist(text="AMERICA")
    b.save()
    b = WatsonBlacklist(text="TIME")
    b.save()
    b = WatsonBlacklist(text="PRODUCER")
    b.save()
    b = WatsonBlacklist(text="CAPITAL DISTRICT")
    b.save()
    b = WatsonBlacklist(text="COMING OUT")
    b.save()
    b = WatsonBlacklist(text="BROOKLYN")
    b.save()
    b = WatsonBlacklist(text="EVENT")
    b.save()
    b = WatsonBlacklist(text="GRADUATION PARTY")
    b.save()
    b = WatsonBlacklist(text="COVER PHOTO")
    b.save()
    b = WatsonBlacklist(text="CHRISTMAS")
    b.save()
    b = WatsonBlacklist(text="THE HOUSE")
    b.save()
    b = WatsonBlacklist(text="UNITED STATES")
    b.save()
    b = WatsonBlacklist(text="BLU-RAY")
    b.save()
    b = WatsonBlacklist(text="HIGH SCHOOL")
    b.save()
    b = WatsonBlacklist(text="INSTAGRAM")
    b.save()
    b = WatsonBlacklist(text="TIMELINE PHOTOS")
    b.save()
    b = WatsonBlacklist(text="GRADUATION")
    b.save()
    b = WatsonBlacklist(text="UNION")
    b.save()
    b = WatsonBlacklist(text="PEOPLE")
    b.save()
    b = WatsonBlacklist(text="MOBILE UPLOADS")
    b.save()
    b = WatsonBlacklist(text="VIRTUAL REALITY FIX")
    b.save()
    b = WatsonBlacklist(text="WORLD")
    b.save()
    b = WatsonBlacklist(text="REALITY")
    b.save()
    b = WatsonBlacklist(text="ENTERTAINMENT FACEBOOK PAGE")
    b.save()
    b = WatsonBlacklist(text="FRIENDS")
    b.save()
    b = WatsonBlacklist(text="NEW PAGE")
    b.save()
    b = WatsonBlacklist(text="APP STORE")
    b.save()
    b = WatsonBlacklist(text="VIDA")
    b.save()
    b = WatsonBlacklist(text="PUBLISHER")
    b.save()
    b = WatsonBlacklist(text="NEW PAGE")
    b.save()
    b = WatsonBlacklist(text="WIFI")
    b.save()
    b = WatsonBlacklist(text="NORTH AMERICA")
    b.save()
    b = WatsonBlacklist(text="ESRB RATING")
    b.save()
    b = WatsonBlacklist(text="OFFICIAL FACEBOOK HOME")
    b.save()
    b = WatsonBlacklist(text="PRESIDENT")
    b.save()
    b = WatsonBlacklist(text="INSTAGRAM PHOTO")
    b.save()
    b = WatsonBlacklist(text="OFFICIAL FACEBOOK ACCOUNT")
    b.save()
    b = WatsonBlacklist(text="VIRTUAL")
    b.save()
    b = WatsonBlacklist(text="ADOLF HITLER")
    b.save()
    b = WatsonBlacklist(text="2 MONTHS")
    b.save()
    b = WatsonBlacklist(text="EN EL")
    b.save()
    b = WatsonBlacklist(text="IPOD")
    b.save()
    b = WatsonBlacklist(text="IPHONE")
    b.save()
    b = WatsonBlacklist(text="ITUNES")
    b.save()
    b = WatsonBlacklist(text="APPLE")
    b.save()
    b = WatsonBlacklist(text="APPLE INC.")
    b.save()


class Migration(migrations.Migration):

    dependencies = [
        ('spaceoutvr', '0007_auto_20161130_1358'),
    ]

    operations = [
        migrations.RunPython(load_blacklist)
    ]
